### ISSUE TITLE
ShowItemLevel: showing item level (1) for all items on battle.net realm game

### ISSUE THREAD

**Issue by AlexSnowLeo** [olegbl/d2rmm.mods#15]
In local game everything works file, but on realm:
![Diablo II_ Resurrected 19 02 2024 14_08_05](https://github.com/olegbl/d2rmm.mods/assets/1458178/d3fad1fa-e499-47dd-a75e-572fd571aabb)

**Comment by olegbl** [comment]
You'll have to talk to Blizzard about that, as this is a game feature that the mod simply turns on.

Plus, I do not support mods being used online - you do so entirely at your own risk.
