### ISSUE TITLE
[CustomItemColors] custom option for rune colors

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm.mods#21]
Hey dude, really liking the changes you're pushing to D2RMM and your mods, looking good!

I noticed all settings now have a custom option except for the newly added rune color options, I guess you forgot those. FYI.

**Comment by olegbl** [comment]
Because those are implemented using localization files (in order to separate high vs mid vs low runes), they cannot support custom colors. It seemed an acceptable trade-off.
